#!/usr/bin/env bash
#
# Generate the Homebrew tap formulae (preso, preso-video) for a published
# release, pinning each platform's tarball URL and sha256.
#
# Usage: scripts/gen-homebrew-formulae.sh <version> <assets-dir> <out-dir>
#   <version>     release version WITHOUT the leading v (e.g. 0.1.0)
#   <assets-dir>  directory holding the four release tarballs:
#                   preso-v<V>-aarch64-apple-darwin[-video].tar.gz
#                   preso-v<V>-x86_64-unknown-linux-gnu[-video].tar.gz
#   <out-dir>     where preso.rb / preso-video.rb are written
#
# Run by .github/workflows/homebrew.yml when a release is published; the
# formulae land in the camjjack/homebrew-preso tap. Binary formulae: brew
# never quarantines curl downloads, so these sidestep Gatekeeper without
# signing. macOS is Apple Silicon only (no Intel release builds); Linux
# covers Linuxbrew on x86_64.
set -euo pipefail

version="$1"
assets="$2"
out="$3"

base="https://github.com/camjjack/preso/releases/download/v${version}"
sha() { shasum -a 256 "$assets/$1" | awk '{print $1}'; }

mac="preso-v${version}-aarch64-apple-darwin.tar.gz"
linux="preso-v${version}-x86_64-unknown-linux-gnu.tar.gz"
mac_video="preso-v${version}-aarch64-apple-darwin-video.tar.gz"
linux_video="preso-v${version}-x86_64-unknown-linux-gnu-video.tar.gz"

mkdir -p "$out"

cat > "$out/preso.rb" <<EOF
# frozen_string_literal: true

# Generated by scripts/gen-homebrew-formulae.sh for v${version}; do not edit.
class Preso < Formula
  desc "Native markdown presentations"
  homepage "https://github.com/camjjack/preso"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac?
    url "${base}/${mac}"
    sha256 "$(sha "$mac")"

    depends_on arch: :arm64
  end

  if OS.linux?
    url "${base}/${linux}"
    sha256 "$(sha "$linux")"

    depends_on arch: :x86_64
  end

  conflicts_with "preso-video", because: "both install a \`preso\` binary"

  def install
    bin.install "preso"
    bin.install "preso-convert"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/preso --version")
  end
end
EOF

cat > "$out/preso-video.rb" <<EOF
# frozen_string_literal: true

# Generated by scripts/gen-homebrew-formulae.sh for v${version}; do not edit.
#
# The --features video build: plays <!-- video: … --> clips inline on the
# slide. Links GStreamer dynamically, so it depends on the gstreamer
# formula (the monorepo build: base/good/bad/ugly/libav plugins included).
class PresoVideo < Formula
  desc "Native markdown presentations (inline video via GStreamer)"
  homepage "https://github.com/camjjack/preso"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac?
    url "${base}/${mac_video}"
    sha256 "$(sha "$mac_video")"

    depends_on arch: :arm64
  end

  if OS.linux?
    url "${base}/${linux_video}"
    sha256 "$(sha "$linux_video")"

    depends_on arch: :x86_64
  end

  depends_on "gstreamer"

  conflicts_with "preso", because: "both install a \`preso\` binary"

  def install
    bin.install "preso"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/preso --version")
  end
end
EOF

echo "wrote $out/preso.rb and $out/preso-video.rb for v${version}"
